import { MarketMovement, SuddenMove } from './types';

export const mockMovements: MarketMovement[] = [
  {
    id: '1',
    title: 'Trump wins 2024 election',
    category: 'POLITICS',
    source: 'Polymarket',
    previousValue: 51,
    currentValue: 59,
    change: 8,
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    volume: 12500000,
  },
  {
    id: '2',
    title: 'BTC above $70k by EOD',
    category: 'CRYPTO',
    source: 'Kalshi',
    previousValue: 71,
    currentValue: 59,
    change: -12,
    timestamp: new Date(Date.now() - 4 * 60 * 1000),
    volume: 450000,
  },
  {
    id: '3',
    title: 'Fed cuts rates in March',
    category: 'ECONOMY',
    source: 'Kalshi',
    previousValue: 44,
    currentValue: 49,
    change: 5,
    timestamp: new Date(Date.now() - 7 * 60 * 1000),
    volume: 890000,
  },
  {
    id: '4',
    title: 'OpenAI releases GPT-5 Q1 2025',
    category: 'TECH',
    source: 'Manifold',
    previousValue: 35,
    currentValue: 28,
    change: -7,
    timestamp: new Date(Date.now() - 12 * 60 * 1000),
    volume: 125000,
  },
  {
    id: '5',
    title: 'Lakers make playoffs',
    category: 'SPORTS',
    source: 'Polymarket',
    previousValue: 62,
    currentValue: 65,
    change: 3,
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    volume: 340000,
  },
  {
    id: '6',
    title: 'ETH/BTC ratio below 0.03',
    category: 'CRYPTO',
    source: 'Polymarket',
    previousValue: 22,
    currentValue: 31,
    change: 9,
    timestamp: new Date(Date.now() - 18 * 60 * 1000),
    volume: 230000,
  },
  {
    id: '7',
    title: 'S&P 500 new ATH this week',
    category: 'ECONOMY',
    source: 'Kalshi',
    previousValue: 41,
    currentValue: 38,
    change: -3,
    timestamp: new Date(Date.now() - 22 * 60 * 1000),
    volume: 1200000,
  },
  {
    id: '8',
    title: 'Twitter rebrand reversed',
    category: 'TECH',
    source: 'Manifold',
    previousValue: 15,
    currentValue: 18,
    change: 3,
    timestamp: new Date(Date.now() - 28 * 60 * 1000),
    volume: 45000,
  },
];

export const mockSuddenMoves: SuddenMove[] = [
  {
    id: '9',
    title: 'Biden health concern announcement',
    category: 'POLITICS',
    source: 'Polymarket',
    previousValue: 20,
    currentValue: 62,
    change: 42,
    timestamp: new Date(Date.now() - 3 * 60 * 1000),
    volume: 8900000,
    alertLevel: 'extreme',
    timeToChange: '34 min',
  },
  {
    id: '10',
    title: 'Major tech acquisition leak',
    category: 'TECH',
    source: 'Kalshi',
    previousValue: 12,
    currentValue: 43,
    change: 31,
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    volume: 560000,
    alertLevel: 'extreme',
    timeToChange: '52 min',
  },
  {
    id: '11',
    title: 'Unexpected Fed statement',
    category: 'ECONOMY',
    source: 'Kalshi',
    previousValue: 68,
    currentValue: 45,
    change: -23,
    timestamp: new Date(Date.now() - 25 * 60 * 1000),
    volume: 2300000,
    alertLevel: 'high',
    timeToChange: '1h 12min',
  },
];